version: '3'
services:
  apigateway:
    build:
      context: ./apigateway-service
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - config
      - discovery

  config:
    build:
      context: ./config-service
      dockerfile: Dockerfile

  discovery:
    build:
      context: ./discovery-service
      dockerfile: Dockerfile

  main:
    build:
      context: ./main-service
      dockerfile: Dockerfile
    depends_on:
      - config
      - discovery
